SELECT Proyecto.Identificacion, Proyecto.id_proyecto, Investigacion.pregunta_investigacion, Investigacion.calidad, Investigacion.objetivo_general FROM Proyecto JOIN Usuario_Proyecto ON Usuario_Proyecto.id_proyecto = Proyecto.id_proyecto JOIN Investigacion ON Investigacion.id_proyecto = Proyecto.id_proyecto WHERE Investigacion.pregunta_investigacion LIKE '%' GROUP BY Proyecto.Identificacion, Proyecto.id_proyecto, Investigacion.pregunta_investigacion, Investigacion.calidad, Investigacion.objetivo_general;
SELECT Proyecto.Identificacion, Proyecto.id_proyecto, Investigacion.pregunta_investigacion, Investigacion.calidad, Investigacion.objetivo_general FROM Proyecto JOIN Usuario_Proyecto ON Usuario_Proyecto.id_proyecto = Proyecto.id_proyecto JOIN Investigacion ON Investigacion.id_proyecto = Proyecto.id_proyecto JOIN Entorno_Investigacion ON Entorno_Investigacion.id_investigacion = Investigacion.id_investigacion WHERE Entorno_Investigacion.descripcion LIKE '%' GROUP BY Proyecto.Identificacion, Proyecto.id_proyecto, Investigacion.pregunta_investigacion, Investigacion.calidad, Investigacion.objetivo_general;
SELECT Proyecto.Identificacion, Proyecto.id_proyecto, Investigacion.pregunta_investigacion, Investigacion.calidad, Investigacion.objetivo_general FROM Proyecto JOIN Usuario_Proyecto ON Usuario_Proyecto.id_proyecto = Proyecto.id_proyecto JOIN Investigacion ON Investigacion.id_proyecto = Proyecto.id_proyecto JOIN Contexto ON Contexto.id_contexto = Investigacion.id_contexto WHERE Contexto.concepcion LIKE '%' GROUP BY Proyecto.Identificacion, Proyecto.id_proyecto, Investigacion.pregunta_investigacion, Investigacion.calidad, Investigacion.objetivo_general;
SELECT * FROM Temporalidad

SELECT Investigacion.*, Contexto.*, Entorno_Investigacion.Descripcion as Entorno_Investigacion, Contexto_Investigacion.nombre as contexto_investigacion, Tipo_Investigacion.nombre as tipo_investigacion, Temporalidad.descripcion as temporalidad FROM Investigacion JOIN Entorno_Investigacion ON Entorno_Investigacion.id_investigacion = Investigacion.id_investigacion JOIN Contexto_Investigacion ON Contexto_Investigacion.id_contexto_investigacion = Entorno_Investigacion.id_contexto_investigacion JOIN Contexto ON Contexto.id_contexto = Investigacion.id_contexto JOIN Temporalidad ON Temporalidad.id_temporalidad = Investigacion.id_temporalidad JOIN Esquema_Formulado ON Esquema_Formulado.id_investigacion = Investigacion.id_investigacion JOIN Pregunta_Modular ON Pregunta_Modular.id_pregunta_modular = Esquema_Formulado.id_pregunta_modular JOIN Tipo_Investigacion ON Tipo_Investigacion.id_tipo_investigacion = Pregunta_Modular.id_tipo_investigacion WHERE Investigacion.id_proyecto = 
SELECT Proyecto.*, Problematica.nombre as problematica, Problematica.descripcion as problematica_descripcion FROM Proyecto JOIN Problematica ON Problematica.id_problematica = Proyecto.id_problematica WHERE Proyecto.id_proyecto = 1
SELECT Causa_Sintoma.* FROM Causa_Sintoma JOIN Problematica ON Problematica.id_problematica = Causa_Sintoma.id_problematica JOIN Proyecto ON Proyecto.id_problematica = Problematica.id_problematica WHERE Proyecto.id_proyecto = 1

SELECT * FROM item;
SELECT * FROM categoria

SELECT 'Justifica el tema/problematica' as item ,(SELECT count(Cita.id_cita) FROM Cita JOIN Direccion_Uso ON Direccion_Uso.id_direccion_uso = Cita.id_direccion_uso JOIN Entidad_Uso ON Entidad_Uso.id_entidad_uso = Direccion_Uso.id_entidad_uso JOIN Unidad_Informacion ON Unidad_Informacion.id_unidad_informacion = Cita.id_unidad_informacion WHERE Entidad_Uso.nombre = 'Problematica' AND Unidad_Informacion.id_proyecto = 1) > 0 as valor
UNION
SELECT 'Justifica el contexto/poblacion, unidad de estudio' as item, (SELECT count(Cita.id_cita) FROM Cita JOIN Direccion_Uso ON Direccion_Uso.id_direccion_uso = Cita.id_direccion_uso JOIN Entidad_Uso ON Entidad_Uso.id_entidad_uso = Direccion_Uso.id_entidad_uso JOIN Unidad_Informacion ON Unidad_Informacion.id_unidad_informacion = Cita.id_unidad_informacion WHERE Entidad_Uso.nombre = 'Contexto' AND Unidad_Informacion.id_proyecto = 1) > 0 as valor
UNION
SELECT 'Justifica tipo de investigacion' as item, (SELECT count(Cita.id_cita) FROM Cita JOIN Direccion_Uso ON Direccion_Uso.id_direccion_uso = Cita.id_direccion_uso JOIN Unidad_Informacion ON Unidad_Informacion.id_unidad_informacion = Cita.id_unidad_informacion WHERE Direccion_Uso.id_entidad_uso = 8 AND Unidad_Informacion.id_proyecto = 1)> 0 as valor
UNION
SELECT 'Tema novedoso no investigado' as item, (SELECT count(Proyecto.id_proyecto) FROM Proyecto WHERE Proyecto.id_problematica = (SELECT Problematica.id_problematica FROM Problematica JOIN Proyecto ON Proyecto.id_problematica = Problematica.id_problematica WHERE Proyecto.id_proyecto = 1) AND Proyecto.id_proyecto < 1) = 0 as valor


SELECT 'No divaga' as item, cast((SELECT count(Cita.id_cita) FROM Cita JOIN Categoria_Uso ON Categoria_Uso.id_categoria_uso = Cita.id_categoria_uso JOIN Unidad_Informacion ON Unidad_Informacion.id_unidad_informacion = Cita.id_unidad_informacion WHERE Unidad_Informacion.id_proyecto = 1 AND Unidad_Informacion.autor = 'Autor' AND Categoria_Uso.id_categoria_uso = 2) as Float) / cast((SELECT count(Cita.id_cita) FROM Cita JOIN Categoria_Uso ON Categoria_Uso.id_categoria_uso = Cita.id_categoria_uso JOIN Unidad_Informacion ON Unidad_Informacion.id_unidad_informacion = Cita.id_unidad_informacion WHERE Unidad_Informacion.id_proyecto = 1 AND Categoria_Uso.id_categoria_uso = 2) as float) as valor FROM Investigacion
UNION
SELECT 'Justifica los eventos' as item, cast((SELECT count(Evento.id_evento) FROM Evento JOIN Evento_Delimitado ON Evento_Delimitado.id_evento = Evento.id_evento JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado JOIN Investigacion ON Investigacion.id_investigacion = Estadio_Aplicado.id_investigacion JOIN Direccion_Uso ON Direccion_Uso.id_entidad = Evento_Delimitado.id_evento_delimitado JOIN Cita ON Cita.id_direccion_uso = Direccion_Uso.id_direccion_uso JOIN Unidad_Informacion ON Unidad_Informacion.id_unidad_informacion = Cita.id_unidad_informacion WHERE Cita.id_categoria_uso = 2 AND Unidad_Informacion.id_proyecto = 1  GROUP BY Evento.id_evento) as float)/cast((SELECT count(Evento.id_evento) FROM Evento JOIN Evento_Delimitado ON Evento_Delimitado.id_evento = Evento.id_evento JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado WHERE Estadio_Aplicado.id_investigacion = 1) as float) as valor FROM Investigacion
UNION
SELECT 'Objetivos especificos completos' as item, cast((SELECT count(Objetivo_Especifico_det.id_objetivo_estadial) FROM Objetivo_Especifico_Det JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Objetivo_Especifico_Det.id_estadio_aplicado JOIN Estadio ON Estadio.id_estadio = Estadio_Aplicado.id_estadio JOIN Objetivo_Estadial ON Objetivo_Estadial.id_objetivo_estadial = Objetivo_Especifico_det.id_objetivo_estadial JOIN Investigacion ON Investigacion.id_investigacion = Estadio_Aplicado.id_investigacion JOIN Modalidad ON Modalidad.id_modalidad = Investigacion.modalidad JOIN Estadio_Estructural ON Estadio_Estructural.id_modalidad = Modalidad.id_modalidad JOIN Objetivo_Especifico ON Objetivo_Especifico.id_estadio_estructural = Estadio_Estructural.id_estadio_Estructural WHERE Estadio_Aplicado.posicion = Estadio_Estructural.posicion AND  Objetivo_Especifico.tipo_objetivo = Objetivo_Estadial.tipo AND Investigacion.id_investigacion = 1) as float)/cast(( SELECT count(Objetivo_Especifico.id_objetivo_especifico) FROM Objetivo_Especifico JOIN Estadio_Estructural ON Estadio_Estructural.id_Estadio_Estructural = Objetivo_Especifico.id_estadio_estructural JOIN Modalidad ON Modalidad.id_modalidad = Estadio_Estructural.id_modalidad JOIN Investigacion ON Investigacion.modalidad = Modalidad.id_modalidad WHERE Investigacion.id_investigacion = 1) as float) as valor FROM Investigacion
UNION
SELECT 'Fuentes variadas' as item, cast((SELECT count(A.id_Base_Noologica) FROM Base_Noologica as A WHERE (SELECT count(Unidad_Informacion.id_unidad_informacion) FROM Unidad_Informacion WHERE Unidad_Informacion.id_proyecto = 1 AND Unidad_Informacion.id_Base_Noologica = A.id_base_Noologica) > 0) as float)/cast((SELECT count(Base_Noologica.id_base_noologica) FROM Base_Noologica) as float) as valor FROM Investigacion
UNION
SELECT 'Conceptualiza los eventos' as item, cast((SELECT count(Evento.id_evento) FROM Evento JOIN Evento_Delimitado ON Evento_Delimitado.id_evento = Evento.id_evento JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado JOIN Investigacion ON Investigacion.id_investigacion = Estadio_Aplicado.id_investigacion JOIN Direccion_Uso ON Direccion_Uso.id_entidad = Evento_Delimitado.id_evento_delimitado JOIN Cita ON Cita.id_direccion_uso = Direccion_Uso.id_direccion_uso JOIN Unidad_Informacion ON Unidad_Informacion.id_unidad_informacion = Cita.id_unidad_informacion WHERE Cita.id_categoria_uso = 3 AND Unidad_Informacion.id_proyecto = 1) as float)/cast((SELECT count(Evento.id_evento) FROM Evento JOIN Evento_Delimitado ON Evento_Delimitado.id_evento = Evento.id_evento JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado WHERE Estadio_Aplicado.id_investigacion = 1) as float) as valor FROM Investigacion
 UNION
SELECT 'Eventos completos' as item, cast((SELECT count(Evento.id_evento) FROM Evento JOIN Evento_Delimitado ON Evento_Delimitado.id_evento = Evento.id_evento JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado JOIN Estadio ON Estadio.id_estadio = Estadio_Aplicado.id_estadio JOIN Investigacion ON Investigacion.id_investigacion = Estadio_Aplicado.id_investigacion JOIN Modalidad ON Modalidad.id_modalidad = Investigacion.modalidad JOIN Estadio_Estructural ON Estadio_Estructural.id_modalidad = Modalidad.id_modalidad JOIN Estructura_Evento ON Estructura_Evento.id_estadio_estructural = Estadio_Estructural.id_estadio_estructural JOIN Clase_Evento_Estructural ON Clase_Evento_Estructural.id_clase_evento_Estructural = Estructura_Evento.id_clase_evento_estructural JOIN Clase_Evento ON Evento_Delimitado.id_clase_evento = Clase_Evento.id_clase_Evento WHERE Estadio_Aplicado.posicion = Estadio_Estructural.posicion AND  Clase_Evento.nombre = Clase_Evento_Estructural.nombre AND Investigacion.id_investigacion = 1) as float)/cast((SELECT count(A.id_Estadio_Estructural) FROM Estadio_Estructural as A JOIN Modalidad ON Modalidad.id_modalidad = A.id_modalidad JOIN Investigacion ON Investigacion.modalidad = Modalidad.id_modalidad WHERE Investigacion.id_investigacion = 1 AND(SELECT count(Estructura_Evento.id_Estructura_evento) FROM Estructura_Evento WHERE A.id_estadio_estructural = Estructura_Evento.id_estadio_estructural) > 0) as float) as valor FROM Investigacion
 UNION
SELECT 'Eventos tienen cuadro de operacionalizacion' as item, cast((SELECT count(A.id_evento_delimitado) FROM Evento_Delimitado as A JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = A.id_estadio_aplicado WHERE (SELECT count(sinergia.id_sinergia) FROM Sinergia  JOIN Aplicacion_Instrumental ON Aplicacion_Instrumental.id_sinergia = Sinergia.id_sinergia WHERE Sinergia.id_evento_delimitado = A.id_evento_delimitado) > 0 AND Estadio_Aplicado.id_investigacion = 1) as float)/cast((SELECT count(A.id_evento_delimitado) FROM Evento_Delimitado as A JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = A.id_Estadio_Aplicado WHERE Estadio_Aplicado.id_investigacion = 1) as float) as valor FROM Investigacion
UNION
SELECT 'Señala las fuentes' as item, cast((SELECT count(A.id_sinergia) FROM Sinergia as A JOIN Evento_Delimitado ON Evento_Delimitado.id_Evento_delimitado = A.id_evento_Delimitado JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado WHERE Estadio_Aplicado.id_investigacion = 1 AND (SELECT count(Fuente.id_fuente) FROM Fuente WHERE Fuente.id_sinergia = A.id_sinergia) > 0)as float)/cast(( SELECT count(A.id_sinergia) FROM Sinergia as A JOIN Evento_Delimitado ON Evento_Delimitado.id_Evento_delimitado = A.id_evento_Delimitado JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado WHERE Estadio_Aplicado.id_investigacion = 1) as float) as valor FROM Investigacion
UNION 
SELECT 'Mide las sinergias' as item, cast((SELECT count(A.id_sinergia) FROM Sinergia as A JOIN Evento_Delimitado ON Evento_Delimitado.id_Evento_delimitado = A.id_evento_Delimitado JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado WHERE Estadio_Aplicado.id_investigacion = 1 AND( SELECT count(Aplicacion_Instrumental.id_aplicacion_instrumental) FROM Aplicacion_Instrumental WHERE Aplicacion_Instrumental.id_sinergia = A.id_sinergia) > 0)as float)/cast((SELECT count(A.id_sinergia) FROM Sinergia as A JOIN Evento_Delimitado ON Evento_Delimitado.id_Evento_delimitado = A.id_evento_Delimitado JOIN Estadio_Aplicado ON Estadio_Aplicado.id_estadio_aplicado = Evento_Delimitado.id_estadio_aplicado WHERE Estadio_Aplicado.id_investigacion = 1) as float) as valor FROM Investigacion